name: Publish and Release

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Adjust version as needed

    - name: Build and Publish
      run: dotnet publish -c Release -r win-x64 --self-contained true --output ./publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Release
        path: ./publish

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: Release
        path: ./publish
    
    - name: Debug - List Release Artifacts
      run: ls -R ./publish/*

    
    # - name: Create release
    #   id: create_release
    #   uses: actions/create-release@latest
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
    #   with:
    #     tag_name: v0.0.1  # Adjust tag name as needed
    #     release_name: Release 0.0.1  # Adjust release name as needed
    #     body: |
    #       Release notes for version 0.0.1



    - name: Upload release assets
      id: upload-release-assets
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/atiaen/opomo-ray/releases/154163448/assets{?name,label}
        asset_path: ./publish/OpomoRay.exe
        asset_name: Opomo-win-x64.zip  # Adjust asset name as needed
        asset_content_type: application/zip
